name: Windows – Clientmanager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Downloading & installing Essentials
        run: |
          # Use headers to mimic a browser and bypass Cloudflare
          $headers = @{
            "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          }
          try {
            Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdpi-fraw/main/Downloads.bat" -OutFile "Downloads.bat" -Headers $headers
            if (Test-Path "Downloads.bat") {
              cmd /c Downloads.bat
            } else {
              Write-Error "Failed to download Downloads.bat"
              exit 1
            }
          } catch {
            Write-Error "Error downloading file: $_"
            exit 1
          }

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
