name: Windows – Clientmanager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      # Step 1: Download file (PowerShell with proper error handling)
      - name: Download Essentials
        run: |
          $ProgressPreference = 'SilentlyContinue'
          try {
              Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdpi-fraw/main/Downloads.bat" -OutFile "Downloads.bat" -UserAgent "Mozilla/5.0"
              if (-not (Test-Path "Downloads.bat")) { throw "Download failed" }
              Write-Output "Download successful"
          } catch {
              Write-Error "Download error: $_"
              exit 1
          }

      # Step 2: Execute files (using CMD with proper syntax)
      - name: Run Installation
        shell: cmd
        run: |
          @echo off
          if exist Downloads.bat (
              call Downloads.bat
          ) else (
              echo ERROR: Downloads.bat missing
              exit /b 1
          )

      - name: Connect to LiteManager
        shell: cmd
        run: |
          @echo off
          if exist show.bat (
              call show.bat
          ) else (
              echo ERROR: show.bat missing
              exit /b 1
          )

      - name: Time Counter
        shell: cmd
        run: |
          @echo off
          if exist loop.bat (
              call loop.bat
          ) else (
              echo ERROR: loop.bat missing
              exit /b 1
          )
