name: Windows – Clientmanager
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Download & install Essentials
        run: |
          curl -L -A "Mozilla/5.0" -o Downloads.bat "https://gitlab.com/chamod12/lm_win-10_github_rdpi-fraw/main/Downloads.bat"
          if exist Downloads.bat (
            cmd /c Downloads.bat
          ) else (
            echo "Error: Failed to download file!"
            exit 1
          )

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
